#
#  Copyright (C) 2026 David Fort <contact@hardening-consulting.com>
#
#  Install rules for a CEF binary distribution, injected by cef.accendino with CMAKE_PROJECT_INCLUDE:
#  the distribution only has a CMake project that builds libcef_dll_wrapper, without any install rule.
#
#  The distribution is installed in the deploy tree as:
#    * <includedir>/cef/include/...: the headers, CEF includes them as "include/cef_xxx.h" so consumers
#      use -I<includedir>/cef
#    * <libdir>/libcef_dll_wrapper.a (or .lib): the wrapper built here
#    * <libdir>/cef/ (<bindir>/cef/ on Windows): libcef with all its runtime files (resources, locales,
#      snapshots, swiftshader, sandbox, ...). They have to stay together as CEF looks for them in the
#      directory of libcef, and it ships its own copy of some generic libraries (libvulkan.so.1, libEGL, ...)
#      that must not shadow the system ones. On Windows the libcef.lib import library is in <libdir>/cef
#    * <libdir>/cmake/CEF/: a CEF package config providing the CEF::libcef and CEF::libcef_dll_wrapper
#      imported targets, and CEF_RUNTIME_DIR pointing at the runtime files to ship with an application
#    * <libdir>/pkgconfig/cef.pc on Linux
#
include(GNUInstallDirs)
include(CMakePackageConfigHelpers)

set(_CEF_INCLUDE_DEST "${CMAKE_INSTALL_INCLUDEDIR}/cef")
set(_CEF_CMAKE_DEST "${CMAKE_INSTALL_LIBDIR}/cmake/CEF")
if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
  set(_CEF_RUNTIME_DEST "${CMAKE_INSTALL_BINDIR}/cef")
else()
  set(_CEF_RUNTIME_DEST "${CMAKE_INSTALL_LIBDIR}/cef")
endif()

set(_CEF_BIN_DIR Release)
if(CMAKE_BUILD_TYPE STREQUAL "Debug" AND EXISTS "${CMAKE_SOURCE_DIR}/Debug")
  set(_CEF_BIN_DIR Debug)
endif()

file(STRINGS "${CMAKE_SOURCE_DIR}/include/cef_version.h" _CEF_VERSION_LINES REGEX "^#define CEF_VERSION(_MAJOR|_MINOR|_PATCH)? ")
foreach(_line ${_CEF_VERSION_LINES})
  if(_line MATCHES "^#define (CEF_VERSION[A-Z_]*) \"?([^\"]+)\"?")
    set(_${CMAKE_MATCH_1} "${CMAKE_MATCH_2}")
  endif()
endforeach()
set(_CEF_NUMERIC_VERSION "${_CEF_VERSION_MAJOR}.${_CEF_VERSION_MINOR}.${_CEF_VERSION_PATCH}")

#
# headers, runtime files, wrapper and docs
#
install(DIRECTORY "${CMAKE_SOURCE_DIR}/include" DESTINATION "${_CEF_INCLUDE_DEST}")

install(DIRECTORY "${CMAKE_SOURCE_DIR}/${_CEF_BIN_DIR}/" DESTINATION "${_CEF_RUNTIME_DEST}" USE_SOURCE_PERMISSIONS
        PATTERN "*.lib" EXCLUDE)
install(DIRECTORY "${CMAKE_SOURCE_DIR}/Resources/" DESTINATION "${_CEF_RUNTIME_DEST}" USE_SOURCE_PERMISSIONS)
if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
  install(FILES "${CMAKE_SOURCE_DIR}/${_CEF_BIN_DIR}/libcef.lib" DESTINATION "${CMAKE_INSTALL_LIBDIR}/cef")
endif()

# the target is created later by the distribution's CMakeLists.txt, the generator expression is resolved
# at generation time
install(FILES "$<TARGET_FILE:libcef_dll_wrapper>" DESTINATION "${CMAKE_INSTALL_LIBDIR}")

install(FILES "${CMAKE_SOURCE_DIR}/LICENSE.txt" "${CMAKE_SOURCE_DIR}/README.txt" DESTINATION "${CMAKE_INSTALL_DOCDIR}")

#
# CMake package config and pkg-config file, generated at the end of the configure step to get the compile
# definitions (CEF_COMPILER_DEFINES) computed by the distribution's cef_variables.cmake
#
function(_cefWritePackageConfig)
  set(CEF_EXPORTED_DEFINES ${CEF_COMPILER_DEFINES})
  file(RELATIVE_PATH CEF_PREFIX_FROM_CONFIG "${CMAKE_INSTALL_PREFIX}/${_CEF_CMAKE_DEST}" "${CMAKE_INSTALL_PREFIX}")
  # the target already has the lib prefix in its name, CEF builds it as libcef_dll_wrapper.a/.lib
  set(CEF_STATIC_LIB_NAME "libcef_dll_wrapper${CMAKE_STATIC_LIBRARY_SUFFIX}")

  file(CONFIGURE OUTPUT "${CMAKE_BINARY_DIR}/CEFConfig.cmake" @ONLY CONTENT [=[
# CEF package config generated by accendino's cef-install.cmake
get_filename_component(_CEF_PREFIX "${CMAKE_CURRENT_LIST_DIR}/@CEF_PREFIX_FROM_CONFIG@" ABSOLUTE)

set(CEF_VERSION_STRING "@_CEF_VERSION@")
set(CEF_INCLUDE_DIR "${_CEF_PREFIX}/@_CEF_INCLUDE_DEST@")
# libcef and the files it needs at runtime, to be shipped next to it
set(CEF_RUNTIME_DIR "${_CEF_PREFIX}/@_CEF_RUNTIME_DEST@")

if(NOT TARGET CEF::libcef)
  if(APPLE)
    # on MacOS the framework is loaded at runtime with CefScopedLibraryLoader and copied in the app bundle,
    # it is not linked
    add_library(CEF::libcef INTERFACE IMPORTED)
  elseif(WIN32)
    add_library(CEF::libcef SHARED IMPORTED)
    set_target_properties(CEF::libcef PROPERTIES
      IMPORTED_LOCATION "${CEF_RUNTIME_DIR}/libcef.dll"
      IMPORTED_IMPLIB "${_CEF_PREFIX}/@CMAKE_INSTALL_LIBDIR@/cef/libcef.lib"
    )
  else()
    add_library(CEF::libcef SHARED IMPORTED)
    set_target_properties(CEF::libcef PROPERTIES
      IMPORTED_LOCATION "${CEF_RUNTIME_DIR}/libcef.so"
    )
  endif()
  set_target_properties(CEF::libcef PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${CEF_INCLUDE_DIR}"
    INTERFACE_COMPILE_DEFINITIONS "@CEF_EXPORTED_DEFINES@"
  )

  add_library(CEF::libcef_dll_wrapper STATIC IMPORTED)
  set_target_properties(CEF::libcef_dll_wrapper PROPERTIES
    IMPORTED_LOCATION "${_CEF_PREFIX}/@CMAKE_INSTALL_LIBDIR@/@CEF_STATIC_LIB_NAME@"
    INTERFACE_LINK_LIBRARIES CEF::libcef
  )
endif()

unset(_CEF_PREFIX)
]=])

  write_basic_package_version_file("${CMAKE_BINARY_DIR}/CEFConfigVersion.cmake"
    VERSION "${_CEF_NUMERIC_VERSION}" COMPATIBILITY SameMajorVersion)

  if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    list(TRANSFORM CEF_EXPORTED_DEFINES PREPEND "-D" OUTPUT_VARIABLE _defines)
    list(JOIN _defines " " _cflags)

    file(WRITE "${CMAKE_BINARY_DIR}/cef.pc"
"prefix=${CMAKE_INSTALL_PREFIX}
includedir=\${prefix}/${_CEF_INCLUDE_DEST}
libdir=\${prefix}/${CMAKE_INSTALL_LIBDIR}
runtimedir=\${prefix}/${_CEF_RUNTIME_DEST}

Name: cef
Description: Chromium Embedded Framework
Version: ${_CEF_VERSION}
Cflags: -I\${includedir} ${_cflags}
Libs: -L\${libdir} -lcef_dll_wrapper -L\${runtimedir} -lcef
")
  endif()
endfunction()

cmake_language(DEFER CALL _cefWritePackageConfig)

install(FILES "${CMAKE_BINARY_DIR}/CEFConfig.cmake" "${CMAKE_BINARY_DIR}/CEFConfigVersion.cmake"
        DESTINATION "${_CEF_CMAKE_DEST}")
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  install(FILES "${CMAKE_BINARY_DIR}/cef.pc" DESTINATION "${CMAKE_INSTALL_LIBDIR}/pkgconfig")
endif()

