name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, next ]
  pull_request:
    branches: [ master, next ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.cfg.os }}

    strategy:
        matrix:
            cfg:
              - { os: Ubuntu-22.04, file: forgiare.accendino, targets: forgiare }
              - { os: Ubuntu-24.04, file: forgiare.accendino, targets: forgiare }
              #- { os: mac-latest,   file: freerdp.accendino,  targets: freerdp2 }
            
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install on ${{ matrix.cfg.os }}
        run: python3 -m pip install .
        
      - name: Test build on ${{ matrix.cfg.os }} with ${{ matrix.cfg.file }}
        run: accendino --prefix=/tmp/ogon --targets=${{ matrix.cfg.targets }} --debug ${{ matrix.cfg.file }}

